"""Signal/portfolio/research-validity metrics, leakage diagnostics,
report rendering (G028).

Public surface: build a :class:`~lasr.reporting.panel.ScoringPanel`
from a G026 ``PredictionSet``, compute signal metrics
(:mod:`~lasr.reporting.signal`), portfolio metrics over a G027 ledger
(:mod:`~lasr.reporting.portfolio_metrics`), coverage-honesty reports
(:mod:`~lasr.reporting.coverage`), research-validity metrics
(:mod:`~lasr.reporting.validity`), and assemble everything into a
banner-carrying :class:`~lasr.reporting.artifact.ReportArtifact`.
"""

from lasr.reporting.artifact import ReportArtifact, render_text
from lasr.reporting.coverage import (
    CoverageAccounting,
    DateAccounting,
    OOSCoverage,
    coverage_accounting,
    oos_coverage,
)
from lasr.reporting.errors import (
    MetricInputError,
    PanelConstructionError,
    ReportingError,
)
from lasr.reporting.panel import (
    DuplicatePolicy,
    PanelExclusion,
    PanelExclusionReason,
    PanelObservation,
    ScoringPanel,
    build_scoring_panel,
)
from lasr.reporting.portfolio_metrics import (
    UNMAPPED_BUCKET,
    CapacityEstimate,
    ExposureSummary,
    GroupContribution,
    GroupExposures,
    ParticipationRate,
    PerformanceByBucket,
    PortfolioSummary,
    TailLosses,
    TurnoverSummary,
    beta_to_benchmark,
    calendar_year_labels,
    capacity_estimate,
    cost_borrow_drag,
    exposure_summary,
    group_exposures,
    max_drawdown,
    participation_rate,
    performance_by_bucket,
    performance_by_group,
    portfolio_summary,
    tail_losses,
    turnover_summary,
)
from lasr.reporting.signal import (
    FactorSelectionStability,
    FeatureFamilyExposure,
    GroupDiagnostics,
    ICSeries,
    ICSummary,
    PredictionDecay,
    QuantileMetrics,
    SignalAutocorrelation,
    SkippedCrossSection,
    SkipReason,
    SubmodelContribution,
    cell_mean_exposure,
    factor_selection_stability,
    feature_family_exposure,
    group_attributable_ic,
    ic_series,
    ic_summary,
    prediction_decay,
    quantile_metrics,
    score_autocorrelation,
    submodel_contribution,
)
from lasr.reporting.types import (
    A003_BANNER,
    NotAvailable,
    ReportModel,
    SyntheticProvenance,
)
from lasr.reporting.validity import (
    BootstrapResult,
    ConfigurationsTested,
    Degradation,
    MultipleTestingDiagnostics,
    SensitivityReport,
    block_bootstrap_mean,
    configurations_tested,
    multiple_testing_diagnostics,
    sensitivity_report,
    validation_to_test_degradation,
)

__all__ = [
    "A003_BANNER",
    "UNMAPPED_BUCKET",
    "BootstrapResult",
    "CapacityEstimate",
    "ConfigurationsTested",
    "CoverageAccounting",
    "DateAccounting",
    "Degradation",
    "DuplicatePolicy",
    "ExposureSummary",
    "FactorSelectionStability",
    "FeatureFamilyExposure",
    "GroupContribution",
    "GroupDiagnostics",
    "GroupExposures",
    "ICSeries",
    "ICSummary",
    "MetricInputError",
    "MultipleTestingDiagnostics",
    "NotAvailable",
    "OOSCoverage",
    "PanelConstructionError",
    "PanelExclusion",
    "PanelExclusionReason",
    "PanelObservation",
    "ParticipationRate",
    "PerformanceByBucket",
    "PortfolioSummary",
    "PredictionDecay",
    "QuantileMetrics",
    "ReportArtifact",
    "ReportModel",
    "ReportingError",
    "ScoringPanel",
    "SensitivityReport",
    "SignalAutocorrelation",
    "SkipReason",
    "SkippedCrossSection",
    "SubmodelContribution",
    "SyntheticProvenance",
    "TailLosses",
    "TurnoverSummary",
    "beta_to_benchmark",
    "block_bootstrap_mean",
    "build_scoring_panel",
    "calendar_year_labels",
    "capacity_estimate",
    "cell_mean_exposure",
    "configurations_tested",
    "cost_borrow_drag",
    "coverage_accounting",
    "exposure_summary",
    "factor_selection_stability",
    "feature_family_exposure",
    "group_attributable_ic",
    "group_exposures",
    "ic_series",
    "ic_summary",
    "max_drawdown",
    "multiple_testing_diagnostics",
    "oos_coverage",
    "participation_rate",
    "performance_by_bucket",
    "performance_by_group",
    "portfolio_summary",
    "prediction_decay",
    "quantile_metrics",
    "render_text",
    "score_autocorrelation",
    "sensitivity_report",
    "submodel_contribution",
    "tail_losses",
    "turnover_summary",
    "validation_to_test_degradation",
]
